version: 2
jobs:
  test:
    docker:
      - image: circleci/php:7.1.14-node-browsers
      - image: circleci/mysql:5.7

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "app/composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: sudo apt-get install -y libicu-dev
      - run: sudo docker-php-ext-install intl
      - run: cd app && composer install -n

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "app/composer.json" }}

workflows:
  version: 2
  test:
    jobs:
      - test
